apiVersion: app/v1
kind: ReplicaSet
metadata: 
  name: myapp-replicaset 
  labels:
    name: myapp
spec:
  selector:
    matchLabels:
      env: production
    replicas: 3
    template:
      metadata:
        name: nginx-2
        labels:
          app: myapp
      spec:
        containers:
          - name: nginx
            image: nginx  